import { ApartmentExpense } from "@/utils/models";
import { v4 as uuidv4 } from "uuid";

export const ApartmentExpensePreset: ApartmentExpense[] = [
  {
    name: "Payroll",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Advertising & Marketing",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "General & Administrative",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Utilities",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Repairs & Maintenance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Service Contracts",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Management Fee",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Taxes",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Insurance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Other CapEx",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Capital Reserve",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
];

export const SelfStorageExpensePreset: ApartmentExpense[] = [
  {
    name: "Payroll",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Advertising & Marketing",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "General & Administrative",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Utilities",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Repairs & Maintenance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Service Contracts",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Management Fee",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Taxes",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Insurance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Other CapEx",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Capital Reserve",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
];

export const SeniorHousingExpensePreset: ApartmentExpense[] = [
  {
    name: "Labor and Benefits",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Advertising & Marketing",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "General & Administrative",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Utilities",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Repairs & Maintenance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Food & Beverage",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Management Fee",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Taxes",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Insurance",
    type: "OpEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Other CapEx",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
  {
    name: "Capital Reserve",
    type: "CapEx",
    cagr: 2.0,
    percent_fixed: 0.0,
    base_amount: 0,
    uniqueId: uuidv4(),
    type_dropdown: false,
  },
];
