import type { Metadata } from "next";
import { Providers } from "./providers";
import { sohne, sohne_mono } from "./theme";

export const metadata: Metadata = {
  title: "Light&Air",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ minHeight: "100vh" }}
      className={`${sohne.variable} ${sohne_mono.variable}`}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
